name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: |
          npm install
          npm run build
        env:
          VITE_GRAPHQL_HTTP_ENDPOINT: ${{ secrets.VITE_GRAPHQL_HTTP_ENDPOINT }}

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: dist
          clean: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  notify:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - uses: snow-actions/line-notify@v1.0.0
        if: always()
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: >
            ${{ github.workflow	}}
            Build <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id	}}> is ${{ needs.build-and-deploy.result }}.

            Project: <https://github.com/${{ github.repository }}>

            Branch: <https://github.com/${{github.repository}}/commits/${{ github.ref_name }}>

            Commit: <https://github.com/${{github.repository}}/commit/${{ github.sha }}>
